import Head from 'next/head'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Digital Brum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contact Page</h1>
    </div>
  )
}